# Generated by Django 5.2.13 on 2026-06-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=11, unique=True, verbose_name='手机号'),
        ),
    ]
