# Generated by Django 5.2.13 on 2026-06-03 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(editable=False, max_length=32, unique=True, verbose_name='订单号')),
                ('start_date', models.DateField(verbose_name='起租日')),
                ('end_date', models.DateField(verbose_name='到期日')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='押金')),
                ('status', models.IntegerField(choices=[(0, '待确认'), (1, '已签约'), (2, '生效中'), (3, '已完成'), (4, '已取消'), (5, '退租中')], default=0, verbose_name='状态')),
                ('contract_content', models.TextField(blank=True, default='', verbose_name='合同内容')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='houses.house', verbose_name='房源')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
    ]
