# Generated by Django 5.2.13 on 2026-06-03 01:57

import apps.orders.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_transaction_order'),
        ('houses', '0002_initial'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(default=apps.orders.models.generate_contract_no, max_length=30, unique=True, verbose_name='合同编号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_sign', '待签约'), ('active', '生效中'), ('expired', '已到期'), ('terminated', '已解约'), ('renewed', '已续签')], default='draft', max_length=15, verbose_name='合同状态')),
                ('property_address', models.CharField(help_text='签约时锁定的完整地址', max_length=200, verbose_name='房屋地址')),
                ('property_area', models.FloatField(verbose_name='房屋面积(㎡)')),
                ('property_desc', models.TextField(blank=True, default='', help_text='家具家电清单、装修状况等', verbose_name='房屋现状及设施')),
                ('start_date', models.DateField(verbose_name='租赁起始日')),
                ('end_date', models.DateField(verbose_name='租赁终止日')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='月租金(元)')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='押金(元)')),
                ('payment_cycle', models.CharField(choices=[('monthly', '月付'), ('quarterly', '季付'), ('semi_annual', '半年付'), ('annual', '年付')], default='quarterly', max_length=15, verbose_name='付款周期')),
                ('payment_day', models.IntegerField(default=1, help_text='每月几号付款', verbose_name='付款日')),
                ('sign_method', models.CharField(choices=[('paper', '纸质签约'), ('electronic', '电子签约')], default='paper', max_length=10, verbose_name='签约方式')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='签约时间')),
                ('contract_pdf', models.FileField(blank=True, default='', upload_to='contracts/', verbose_name='合同PDF')),
                ('move_in_date', models.DateField(blank=True, null=True, verbose_name='实际入住日')),
                ('move_in_water', models.FloatField(blank=True, null=True, verbose_name='入住水表读数')),
                ('move_in_electric', models.FloatField(blank=True, null=True, verbose_name='入住电表读数')),
                ('move_in_gas', models.FloatField(blank=True, null=True, verbose_name='入住燃气表读数')),
                ('move_in_notes', models.TextField(blank=True, default='', verbose_name='入住验收备注')),
                ('move_out_date', models.DateField(blank=True, null=True, verbose_name='实际退房日')),
                ('move_out_water', models.FloatField(blank=True, null=True, verbose_name='退房水表读数')),
                ('move_out_electric', models.FloatField(blank=True, null=True, verbose_name='退房电表读数')),
                ('move_out_gas', models.FloatField(blank=True, null=True, verbose_name='退房燃气表读数')),
                ('move_out_notes', models.TextField(blank=True, default='', verbose_name='退房验收备注')),
                ('deposit_refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='押金退还金额')),
                ('deposit_refund_date', models.DateField(blank=True, null=True, verbose_name='押金退还日期')),
                ('termination_reason', models.TextField(blank=True, default='', verbose_name='解约原因')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='解约日期')),
                ('early_termination_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='违约金')),
                ('renewal_count', models.IntegerField(default=0, verbose_name='续签次数')),
                ('government_filing_status', models.CharField(default='pending', help_text='pending/filed/not_required', max_length=10, verbose_name='备案状态')),
                ('government_filing_number', models.CharField(blank=True, default='', max_length=50, verbose_name='备案编号')),
                ('special_terms', models.TextField(blank=True, default='', help_text='宠物条款、装修限制、转租规则等', verbose_name='特别约定')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='houses.house', verbose_name='租赁房屋')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_contracts', to=settings.AUTH_USER_MODEL, verbose_name='甲方(出租方)')),
                ('parent_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='orders.contract', verbose_name='原合同(续签用)')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_contracts', to=settings.AUTH_USER_MODEL, verbose_name='乙方(承租方)')),
            ],
            options={
                'verbose_name': '租赁合同',
                'verbose_name_plural': '租赁合同',
                'db_table': 'contract',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='账期开始')),
                ('period_end', models.DateField(verbose_name='账期结束')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='应付金额')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实付金额')),
                ('due_date', models.DateField(verbose_name='应付日期')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('payment_method', models.CharField(blank=True, default='', help_text='微信/支付宝/银行转账/平台钱包', max_length=20, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('overdue', '已逾期'), ('confirmed', '已确认')], default='pending', max_length=10, verbose_name='状态')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.contract', verbose_name='合同')),
            ],
            options={
                'verbose_name': '租金缴纳',
                'verbose_name_plural': '租金缴纳',
                'db_table': 'rent_payment',
                'ordering': ['period_start'],
            },
        ),
        migrations.CreateModel(
            name='ViewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.DateField(verbose_name='预约看房日期')),
                ('view_time', models.CharField(help_text='如: 10:00-11:00', max_length=20, verbose_name='预约时间段')),
                ('contact_phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('completed', '已看房'), ('cancelled', '已取消')], default='pending', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_requests', to='houses.house', verbose_name='房源')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_requests', to=settings.AUTH_USER_MODEL, verbose_name='租客')),
            ],
            options={
                'verbose_name': '看房预约',
                'verbose_name_plural': '看房预约',
                'db_table': 'view_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
