# Generated by Django 5.2.13 on 2026-06-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='正=收入/负=支出', max_digits=10, verbose_name='金额')),
                ('type', models.CharField(choices=[('rent', '租金'), ('deposit', '押金'), ('refund', '退款'), ('recharge', '充值')], max_length=10, verbose_name='类型')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '收支明细',
                'verbose_name_plural': '收支明细',
                'db_table': 'transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
