# Generated by Django 5.2.13 on 2026-06-03 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
    ]
