# Generated by Django 5.2.13 on 2026-06-03 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_transaction_order'),
        ('orders', '0003_contract_rentpayment_viewrequest_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.contract', verbose_name='关联合同'),
        ),
    ]
