# Generated by Django 5.2.13 on 2026-06-03 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='区域名称')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域',
                'db_table': 'district',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'favorite',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='详细描述')),
                ('summary', models.CharField(blank=True, default='', max_length=200, verbose_name='摘要')),
                ('community', models.CharField(blank=True, default='', max_length=50, verbose_name='小区名')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='详细地址')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='月租金(元)')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='押金(元)')),
                ('area_size', models.FloatField(verbose_name='面积(㎡)')),
                ('room_count', models.IntegerField(default=1, verbose_name='卧室数')),
                ('hall_count', models.IntegerField(default=1, verbose_name='客厅数')),
                ('toilet_count', models.IntegerField(default=1, verbose_name='卫生间数')),
                ('layout_desc', models.CharField(blank=True, default='', max_length=20, verbose_name='户型描述')),
                ('floor', models.IntegerField(default=1, verbose_name='当前楼层')),
                ('total_floors', models.IntegerField(default=1, verbose_name='总楼层')),
                ('floor_level', models.CharField(blank=True, default='', help_text='低楼层/中楼层/高楼层', max_length=5, verbose_name='楼层等级')),
                ('orientation', models.CharField(blank=True, default='', help_text='南/北/东/西/南北/东南/西南', max_length=10, verbose_name='朝向')),
                ('decoration', models.CharField(blank=True, default='', help_text='毛坯/简装/精装/豪装', max_length=10, verbose_name='装修')),
                ('has_elevator', models.BooleanField(default=False, verbose_name='有电梯')),
                ('has_subway', models.BooleanField(default=False, verbose_name='近地铁')),
                ('facilities', models.JSONField(blank=True, default=list, help_text='["空调","冰箱","洗衣机","WiFi"]', verbose_name='配套设施')),
                ('pay_type', models.CharField(blank=True, default='', help_text='押一付一/押一付三', max_length=10, verbose_name='付款方式')),
                ('lease_term', models.CharField(blank=True, default='', help_text='月租/年租/1-3个月', max_length=20, verbose_name='租期')),
                ('status', models.IntegerField(choices=[(0, '出租中'), (1, '已租出'), (2, '已下架')], default=0, verbose_name='状态')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='推荐')),
                ('is_sticky', models.BooleanField(default=False, verbose_name='置顶')),
                ('is_new', models.BooleanField(default=False, verbose_name='新上')),
                ('is_vr', models.BooleanField(default=False, verbose_name='VR房源')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('favorite_count', models.IntegerField(default=0, verbose_name='收藏数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '房源',
                'verbose_name_plural': '房源',
                'db_table': 'house',
                'ordering': ['-is_sticky', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HouseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='分类名称')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
            ],
            options={
                'verbose_name': '房屋分类',
                'verbose_name_plural': '房屋分类',
                'db_table': 'house_category',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='houses/', verbose_name='图片')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '房源图片',
                'verbose_name_plural': '房源图片',
                'db_table': 'house_image',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='商圈名称')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='houses.district', verbose_name='所属区域')),
            ],
            options={
                'verbose_name': '商圈',
                'verbose_name_plural': '商圈',
                'db_table': 'area',
                'ordering': ['sort'],
            },
        ),
    ]
