# Generated by Django 5.2.13 on 2026-06-03 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('orientation', '朝向'), ('decoration', '装修'), ('pay_type', '付款方式'), ('lease_term', '租期'), ('facility', '配套设施'), ('community', '小区名')], db_index=True, max_length=20, verbose_name='分组')),
                ('label', models.CharField(max_length=50, verbose_name='显示名')),
                ('value', models.CharField(max_length=50, verbose_name='值')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('area', models.ForeignKey(blank=True, help_text='仅小区名分组需要关联商圈', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='houses.area', verbose_name='所属商圈')),
            ],
            options={
                'verbose_name': '字典',
                'verbose_name_plural': '字典',
                'db_table': 'dictionary',
                'ordering': ['group', 'sort'],
                'unique_together': {('group', 'value')},
            },
        ),
    ]
